### PR TITLE
feat: add chroma component

### PR DESCRIPTION
**Pull request by zidanehakim**
Because

- We want to integrate VDP with chroma self hosted vector db
- We want more vector db component choice

This commit

- Add chroma component along with the basic tasks (query, upsert, ..)
- Use api key auth that user determine themselves

### CODE REVIEW

**Comment by zidanehakim** [comment]
Note:

This PR will be drafted while waiting for the chroma logo

**Review by GeorgeWilliamStrong — COMMENTED** [review]
From documentation perspective, LGTM!

**Review by chuang8511 — COMMENTED** [review]
Hi @zidanehakim 
If you'd like to fix it, please let me know.
If you do not have time, please also let me know. I will take over it!

**Comment by zidanehakim** [comment]
@chuang8511 Please check the changes i've made, thank you

**Review by chuang8511 — COMMENTED** [review]
lgtm.

**Comment by chuang8511** [comment]
@zidanehakim   cc @kuroxx 
Thanks for your contribution!
Could you provide your recipe when you test this component?
So, Anni or I can use it as a reference to verify it and use it as the marketing content!

**Comment by zidanehakim** [comment]
@chuang8511 

Sure, I did test it using the earlier version of instill-core rather than using the latest no-code pipeline, so it might be a little bit different. The way I tested it is by testing the output for different tasks one by one

NOTE: the url is my self host aws ec2 chroma url which now has been terminated

```
{
  "version": "v1beta",
  "component": {
    "chroma-0": {
      "task": "TASK_QUERY",
      "type": "chroma",
      "input": {
        "collection-name": "testqueryembedding2",
        "n-results": 100,
        "vector": "${[0.1,0.2]}"
      },
      "setup": {
        "api-key": "${secret.chromaapikey}",
        "url": "http://3.25.202.142:8000"
      }
    }
  },
  "variable": {
    "a": {
      "instillFormat": "semi-structured/json",
      "title": "a"
    }
  },
  "output": {
    "b": {
      "title": "b",
      "value": "${chroma-0.output}"
    }
  }
}
```

**Pull request merged**
