### PR TITLE
feat(text): add tokenizer for cohere & new gpt-4o

### PR DESCRIPTION
**Pull request by chuang8511**
Because

- users will need to count the token count for each chunk
- token chunk strategy and token count should decouple
- users will need to fetch tokeniser from vendors

This commit

- add tokenisation for cohere & gpt-4o family
    - p.s. there are more use cases in huggingface. it will cause error when the setting is not correct for huggingface python lib.
    - e.g. the token count is over the limitation for a specific model
- refactor text task chunk text for future extensibility and maintainability
- remove model from all chunking strategies

note
- we will need to have a better way to organise the python code and executors

### CODE REVIEW

**Comment by chuang8511** [comment]
I will rebase it in sprint 43

**Comment by donch1989** [comment]
Hi @chuang8511 
Will this change need any recipe migration?

**Comment by chuang8511** [comment]
@donch1989 

> Will this change need any recipe migration?

Yes, so I did https://github.com/instill-ai/pipeline-backend/pull/590

**Review by donch1989 — APPROVED** [review]

**Comment by donch1989** [comment]
@chuang8511 
Please rebase and merge it. Thanks.

**Comment by chuang8511** [comment]
I will redo this PR because I changed a bit in https://github.com/instill-ai/component/pull/317

**Pull request closed without merging**
