### PR TITLE
feat: add Fireworks AI component

### PR DESCRIPTION
**Pull request by namwoam**
Because

- We want to integrate Fireworks AI Client into our VDP pipeline platform.

This commit

- Added the Fireworks AI Component, which supports the following tasks: 
    - (a)  TASK_TEXT_GENERATION_CHAT
    Models: llama3.1 (405b, 70b, 9b), llama3 (70b, 8b), gemma2-9b,  phi-3-vision-128K, deepseek-coder, qwen2 (72b) and more 
    - (b) TASK_TEXT_EMBEDDINGS
    Models: nomic-ai/nomic-embed, thenlper/gte, WhereIsAI/UAE

API Documentation: https://docs.fireworks.ai/api-reference/introduction
Pricing Documentation: https://fireworks.ai/pricing

### CODE REVIEW

**Comment by namwoam** [comment]
image

Above is the performance of llama3-70b-it across different providers. This sector is extremely competitive and I am not sure if we will support all the providers?

**Review by chuang8511 — APPROVED** [review]
lgtm.

**Comment by chuang8511** [comment]
@namwoam 
Btw, does Fireworks have their official tokenizer that we can use?
It will be used in Text Component ChunkTask

**Comment by namwoam** [comment]
All their model are open sourced, so I guess it could be imported from huggingface?

**Comment by chuang8511** [comment]
@namwoam 
Could you help me check the pricing?
I am not sure these models' params count.
image

image


<google-sheets-html-origin><style type="text/css"></style>
deepseek-coder-v2-instruct
--
deepseek-coder-v2-lite-instruct
starcoder-16b
starcoder-7b
phi-3-vision-128k-instruct
qwen2-72b-instruct
mythomax-l2-13b
nomic-ai/nomic-embed-text-v1.5
nomic-ai/nomic-embed-text-v1
WhereIsAI/UAE-Large-V1
thenlper/gte-large
thenlper/gte-base

**Comment by namwoam** [comment]
Hello, the pricing are as follows:

Text models:

1. deepseek-coder-v2-instruct: 236b MoE
2. deepseek-coder-v2-lite-instruct: 16b MoE source: [huggingface](https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct)
3. phi-3-vision-128k-instruct: 4.2b source: [phi3 technical report](https://arxiv.org/abs/2404.14219) under section 6.1

Embedding models:

1. nomic-embed-text-v1.5: 137m source: [huggingface](https://huggingface.co/nomic-ai/nomic-embed-text-v1.5)
2. nomic-embed-text-v1: 137m source: [huggingface](https://huggingface.co/nomic-ai/nomic-embed-text-v1)
3. UAE-Large-V1: 335m source: [huggingface](https://huggingface.co/WhereIsAI/UAE-Large-V1)
4. gte-large: 335m source: [huggingface](https://huggingface.co/thenlper/gte-large)
5. gte-base: 109m source: [huggingface](https://huggingface.co/thenlper/gte-base)

The pricing for embedding models:
image

**Comment by chuang8511** [comment]
@namwoam 
I still cannot match which price is correct. I will take out from Instill Credit first.
Please help us check it again. Thank you.
- deepseek-coder-v2-instruct: 236b MoE
image


✅ deepseek-coder-v2-lite-instruct: 16b MoE source: [huggingface](https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct)
-> 0.5
✅ phi-3-vision-128k-instruct: 4.2b source: [phi3 technical report](https://arxiv.org/abs/2404.14219) under section 6.1
image
-> 0.2

**Comment by namwoam** [comment]
Ok, no problem.

**Pull request merged**
